spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: *****
    username: ***
    password: ***
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 80

mybatis:
  type-aliases-package: com.pojo
