spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.229.193:3306/homework?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lzj2002517
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 80

mybatis:
  type-aliases-package: com.pojo
